### ISSUE TITLE
On Android app getting Error from detectSpoof() method

### ISSUE THREAD

**Issue by mdilawar02** [getchui/sample-apps#145]
All other functions like detectMask, detectGlasses, detectLargestFace are working as expected. But when I'm calling this method detectSpoof I'm getting following error. Also on detectBlink method getting same type of error
`Unable to open model file`
**My Error:**
E/libc++abi: terminating with uncaught exception of type std::runtime_error: Unable to open model file (spoof_v5.trueface.enc). Be sure to run download_spoof.sh and set the modelsPath correctly
A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 18061 (FrameExecutor #), pid 15349 (lin.everid.free)

**Block of code:**
```
val configurationOptions = ConfigurationOptions()
configurationOptions.smallestFaceWidth = 120
val sdk = SDK(requireContext(),configurationOptions)
val isLicensed: Boolean = sdk.setLicense("MY_TOKEN_KEY")
sdk.setImage(size.width, size.height, data)
val faceBoxAndLandmarks = sdk.detectLargestFace()
try {
        val glasses = sdk.detectGlasses(faceBoxAndLandmarks)  //This line is working as expected
        var glassesValue=glasses.name
        
        val spoof=sdk.detectSpoof(faceBoxAndLandmarks)    //Getting error at this line
        var spoofValue=spoof.score
}catch (t: Throwable) {
        t.printStackTrace()
}
```

**Comment by netdur** [comment]
Hello @mdilawar02 , Please download spoof model and place it inside assets folder
https://trueface-libraries-docs.web.app/doc/android/setup#models
